export enum EnumCategoriaFiltro {
    TODOS,
    VOLUMEN,
    PRECIO_Y_MOVIMIENTO,
    VOLATILIDAD,
    MOMENTUM_E_INDICADORES_TECNICOS,
    CARACTERISTICAS_FUNDAMENTALES,
    TIEMPO_Y_PATRONES_DE_PRECIO,
}