export enum EnumCategoriaFiltro {
    TODOS = "TODOS",
    VOLUMEN = "VOLUMEN",
    PRECIO_Y_MOVIMIENTO = "PRECIO_Y_MOVIMIENTO",
    VOLATILIDAD = "VOLATILIDAD",
    MOMENTUM_E_INDICADORES_TECNICOS = "MOMENTUM_E_INDICADORES_TECNICOS",
    CARACTERISTICAS_FUNDAMENTALES = "CARACTERISTICAS_FUNDAMENTALES",
    TIEMPO_Y_PATRONES_DE_PRECIO = "TIEMPO_Y_PATRONES_DE_PRECIO",
}